<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7368" started-at="2019-07-29T18:41:25Z" finished-at="2019-07-29T18:41:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7368" started-at="2019-07-29T18:41:25Z" finished-at="2019-07-29T18:41:33Z">
      <class name="example.TestNGTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:example.TestNGTest@3ffc5af1]" name="beforeTest" is-config="true" duration-ms="5769" started-at="2019-07-30T02:41:25Z" finished-at="2019-07-30T02:41:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="test()[pri:0, instance:example.TestNGTest@3ffc5af1]" name="test" duration-ms="889" started-at="2019-07-30T02:41:31Z" finished-at="2019-07-30T02:41:32Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: at org.testng.AssertJUnit.fail(AssertJUnit.java:59)at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)at example.TestNGTest.test(TestNGTest.java:15)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:example.TestNGTest@3ffc5af1]" name="afterTest" is-config="true" duration-ms="679" started-at="2019-07-30T02:41:32Z" finished-at="2019-07-30T02:41:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- example.TestNGTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
